### PR TITLE
update DALNet results

### PR DESCRIPTION
**Pull request by Yzichen**

### CODE REVIEW

**Review by karstenBehrendt — APPROVED** [review]
Numbers match evaluation results

**Comment by karstenBehrendt** [comment]
@Yzichen Thanks for submitting the pull request!

**Comment by Yzichen** [comment]
@karstenBehrendt 谢谢你的指导，顺便问一下，什么时候能在网站上看到更新？

**Comment by karstenBehrendt** [comment]
Should be in there by now.

**Pull request merged**
